### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by kepi** [msimerson/sentry#5]
It would be great to have support for IPv6.

**Comment by msimerson** [comment]
There is already some support for IPv6 but you must have Net::IP installed. 

If you have a particular issue with IPv6 addresses not working as expected, then file a specific PR with realistic data that *should* be detected and is not. Example data would be log file entries.

**Comment by msimerson** [comment]
FWIW, this is my home IPv6 IP and sentry tracks it just fine:

````
sudo /var/db/sentry/sentry.pl --ip=2601:602:9000:95:1195:f401:eaf6:7dee -r
 255 connections from 2601:602:9000:95:1195:f401:eaf6:7dee (key: 687865856)
	and it is whitelisted
````
