### ISSUE TITLE
Automatic Uninstall Method

### ISSUE THREAD

**Issue by IWriteThings** [msimerson/sentry#6]
### Sentry version
our $VERSION = '1.04';
### Expected behavior
sentry --uninstall
Should completely and cleanly remove the module and disconnect it from the system.
### Observed behavior
Nothing happens

**Comment by msimerson** [comment]
I won't be implementing this. `<opinion>`I think wrong headed to include software uninstallers on *nix platforms. `</opinion>` What % of *nix software includes an uninstall feature? There are better ways (thin provisioning, re-deploys, containers (jail, docker, etc..).

PRs welcome.
