### ISSUE TITLE
Sentry whitelist command doesn't seem to work.

### ISSUE THREAD

**Issue by geoidesic** [msimerson/sentry#8]
### Sentry version
1.0.5 (on CentOS 8)

### Expected behavior
Should whitelist the IP address

### Observed behavior
[root@localhost ~]# /var/db/sentry/sentry.pl --ip=N.N.N.N --whitelist
Net::IP not installed. No IPv6 support.
Can't locate object method "new" via package "Net::IP" at /var/db/sentry/sentry.pl line 931.

### Steps to reproduce
Installed as per instructions. Ran the above command with a valid IP address.

**Comment by msimerson** [comment]
That was a bug, sorry. It is fixed in #10 which will be merged shortly.
